### ISSUE TITLE
Search for movies in non-English langauges

### ISSUE THREAD

**Issue by clinton-hall** [CouchPotato/CouchPotatoServer#1300]
Hi RuudBurger,

Another one that has popped up a  few times in the forums.

When searching for a movie in a foreign (non-English) language the movie is found and displayed in English. not really a problem. 

I have seen a few posts about not naming an English movie in another language etc, but the issue here is that a lot of releases are named in the language of the primary audio track...

In nzbmatrix I know it was searching for the ttxxxx imdb id, so regardless of the movie name in the release, it would find an Italian or German movie and particularly if Italian or German were set as required words it would get the right movie...But...

For other providers (and particularly torrents) am I correct in stating that it actually searches by movie name? In this case it only finds a movie if the release is named with the English name and then includes another language (audio track) in the release name... Again, with torrents it seems that most releases that are in Italian or German are actually named with the Italian or German movie name...

So, would it be possible to track the "AKA" title that the original movie search was done under and use both the English and AKA name for the search? Or would it be possible to add a location / language at the time of adding the movie to achieve the same?

I'll try and take a look at these myself.. but obviously I haven't been looking at code lately (just trying to keep on top of forum posts) and thought you might be able to quickly squash these ideas, confirm a better method, or suggest which way to go about trying to tackle this...

**Comment by neothematrix** [comment]
for anybody not scared of manual code edits, clinton-hall's manual modification can now be reproduced with this patch (I forced italian language "it" as first choice):

```
diff --git a/couchpotato/core/media/movie/providers/info/themoviedb.py b/couchpotato/core/media/movie/providers/info/themoviedb.py
index 713d505..5d25cee 100644
--- a/couchpotato/core/media/movie/providers/info/themoviedb.py
+++ b/couchpotato/core/media/movie/providers/info/themoviedb.py
@@ -47,6 +47,7 @@ class TheMovieDb(MovieProvider):
             raw = self.request('search/movie', {
                 'query': name_year.get('name', q),
                 'year': name_year.get('year'),
+                'language': 'it',
                 'search_type': 'ngram' if limit > 1 else 'phrase'
             }, return_key = 'results')
         except:
@@ -90,6 +91,7 @@ class TheMovieDb(MovieProvider):

         # Do request, append other items
         movie = self.request('movie/%s' % movie.get('id'), {
+            'language': 'it',
             'append_to_response': 'alternative_titles' + (',images,casts' if extended else '')
         })
         if not movie:
```

it would be awesome if a similar patch, including a configuration option dropdown with all the languages, could be implemented into the mainstream.

**Comment by neothematrix** [comment]
another option could be to ask themoviedb every translated title, one by one, since the api right now doesn't allow to retrieve all the translated titles in one request, it works, but it's very slow:

```
diff --git a/couchpotato/core/media/movie/providers/info/themoviedb.py b/couchpotato/core/media/movie/providers/info/themoviedb.py
index 713d505..f714d17 100644
--- a/couchpotato/core/media/movie/providers/info/themoviedb.py
+++ b/couchpotato/core/media/movie/providers/info/themoviedb.py
@@ -90,7 +90,7 @@ class TheMovieDb(MovieProvider):

         # Do request, append other items
         movie = self.request('movie/%s' % movie.get('id'), {
-            'append_to_response': 'alternative_titles' + (',images,casts' if extended else '')
+            'append_to_response': 'alternative_titles,translations' + (',images,casts' if extended else '')
         })
         if not movie:
             return
@@ -161,6 +161,16 @@ class TheMovieDb(MovieProvider):
         # Add alternative titles
         alternate_titles = movie.get('alternative_titles', {}).get('titles', [])

+        # Add translated titles
+        translations = movie.get('translations').get('translations')
+        for translation in translations:
+            if translation['iso_639_1'] != "en":
+               tran_movie = self.request('movie/%s' % movie.get('id'), {
+                    'language': translation['iso_639_1']
+                })
+                if tran_movie:
+                   alternate_titles.append(tran_movie['title'])
+
         for alt in alternate_titles:
             alt_name = alt.get('title')
             if alt_name and alt_name not in movie_data['titles'] and alt_name.lower() != 'none' and alt_name is not None:
```

**Comment by ToneStrife** [comment]
Hi,

I have tried the first solution but the OMDB is looking for an english title and torrent providers are looking for this.

What am I doing worng? 

Maybe is a problelm with the API Key of TMDB, where do I need to write it?

**Comment by neothematrix** [comment]
For already queued movies, you'll need to edit the movie (by clicking the little pencil icon) and chose the title from the dropdown, the dropdown should now show your selected language title translations.
For new movies search, just make sure to select the title in your language before adding the movie to your queue.

**Comment by ToneStrife** [comment]
Thank you! 
Right now I have the movies in Spanish in my list, but when looking for torrents it is still searching only the english title.

For example

01-30 08:41:48INFO[core.media.movie.searcher] Search for Regreso al Futuro in 720p ignoring ETA
01-30 08:41:53INFO[core.media.movie.searcher] Search for Regreso al Futuro in 1080p ignoring ETA
01-30 08:41:55INFO[edia._base.providers.base] Found: score(1184) on KickAssTorrents: Back To The Future 25th Anniversary Trilogy 1080p BluRay x264 an
01-30 08:41:55INFO[edia._base.providers.base] Found: score(256) on KickAssTorrents: Back to the Future 1 (1985) 1080p MKV x264 (NL sub) LD TBS

**Comment by neothematrix** [comment]
kickasstorrents searches using the imdb id, not the title (so you don't really need the mod if you're using only KAT search provider, you should use some title based search providers, like torrentz.eu for example), so it's perfectly normal that you see results in other languages, you need to add some "required and preferred keywords" in CouchPotato search filters, i.e.: "spa, spanish" so that couchpotato will make sure to grab the correct releases only.
You can do that in couchpotato -> settings -> searcher -> categories, these are the words I put to look for italian movies:
Preferred: ita, italian
Required: ita, italian

what will happen then, is that even if CP is searching on kickasstorrent using the imdbid, it will find the english title, which is fine, but it will ignore it since it doesn't contain the "spa" or "spanish" keyowrds.

I hope it helps.

**Comment by ToneStrife** [comment]
Thank you, I have changed the torrent provider but now no results appear. The torrent is not findings any torrent.
I think is a problem with torrentz. Are there any other providers that use title instead of IMDB Id?
Am I doing anything wrong with torrentz.eu?

**Comment by neothematrix** [comment]
by default torrentz.eu searcher in couchpotato only searches for "verified" torrent, have you tried manually searching for the movie on torrentz.eu? it doesn't return anything as "verified" torrent for "regreso al futuro" (there's a "verify" filter on the top right part of torrentz.eu website).
You can remove that restriction in CP torrentz.eu search configuration, but you need to enable "advanced settings", then a new option for torrentz.eu searcher will appear "verified only", you can uncheck it and try again.

**Comment by muhahacz** [comment]
@RuudBurger 
Please merge it to master branch, 
https://github.com/CouchPotato/CouchPotatoServer/issues/1300#issuecomment-67638247

**Comment by fabio166** [comment]
Hi, I don' know well the app code but I think there could be something wrong with the languages. I have changed the default language in the "themoviedb.py" file from 'en' to 'it'. What I expect is that couchpotato asks themoviedb for the italian title, as well as the english original title, in order to find torrent results based on the italian title, also without selecting the italian title in the title dropdown of the film. However, the request to themoviedb with 'language=it' is done but no searches with the italian title are executed.

For example, please consider "X-men: Apocalypse" (original title). Couchpotato makes correctly the request to themoviedb (https://api.themoviedb.org/3/movie/246655?api_key=xxx&append_to_response=alternative_titles&language=it) but then it searches the original title only although the answer of themoviedb ('title' parameter) is "X-men: Apocalisse".

Is there something that I'm missing?

Thank you for your effort

**Comment by neothematrix** [comment]
@fabio166 revert your changes, make sure you're using the latest commit version of CouchPotato, the one including the #6482 merge and change your settings.conf, under the [core] section add a "language=it" parameter and restart CouchPotato.

**Comment by fabio166** [comment]
Oh many thanks, I had tried under [themoviedb] section but it doesn't work, tonight I'll follow your indications!

**Comment by fabio166** [comment]
Last master build has those changes but after editing "settings.conf" I get this error (the app is installed on a Synology nas): 

[ couchpotato.core.event] Error in event "app.load", that wasn't caught: Traceback (most recent call last): File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/couchpotato/core/event.py", line 15, in runHandler return handler(*args, **kwargs) File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/couchpotato/core/media/movie/providers/info/themoviedb.py", line 57, in config languages.remove(self.default_language) ValueError: list.remove(x): x not in list encoding=UTF-8 debug=False args=['--daemon', '--pid_file', '/usr/local/couchpotatoserver/var/couchpotatoserver.pid', '--config_file', '/usr/local/couchpotatoserver/var/settings.conf'] app_dir=/usr/local/couchpotatoserver/share/CouchPotatoServer data_dir=/usr/local/couchpotatoserver/var desktop=None options=Namespace(config_file='/usr/local/couchpotatoserver/var/settings.conf', console_log=False, daemon=True, data_dir=None, debug=False, pid_file='/usr/local/couchpotatoserver/var/couchpotatoserver.pid', quiet=False)

**Comment by fabio166** [comment]
Ok I got it, the right option is "languages=it"

**Comment by fabio166** [comment]
Unfortunately, the behavior is the same as by changing the language in the py file directly. The connection to themoviedb.org is correct (both en and it) but couchpotato seems to search for the english title only. An example is "X-men: Apocalypse", as I wrote before.
