### ISSUE TITLE
[REQ] Proper (foreign) language support based on user preference

### ISSUE THREAD

**Issue by piejanssens** [CouchPotato/CouchPotatoServer#1862]
Now the user has to add a bunch of foreign languages to the ignore words otherwise chances are high you snatch an English movie with German or French dubbed audio. That's fine, but this also blocks CP from snatchin real foreign movies when you add those. 

My suggestion is to add a section to that same settings page where you can add your own language tags. 
You can add rows for as many lanuages as you want. Every language you add here will have the same effect as adding it to the ignore words list except in case the movie's original audio is in that language. E.g. when I'm looking for a real French movie, I want to watch that movie in French.

This is only possible of course when CP has the information on a movies original audio language.

**Comment by Twanislas** [comment]
Friendly *bump* :)

**Comment by piejanssens** [comment]
Supported by using categories where you remove the foreign ignore words.
