### ISSUE TITLE
CP not snatching the highest quality first

### ISSUE THREAD

**Issue by achandab** [CouchPotato/CouchPotatoServer#6529]
### Steps to reproduce:
1. Setup so a movie downloads 720p, 1080p,BR-DISK, 2140p
2. Search for movie
3. Will find BR-DISK and 2140p
4. Will download BR-DISK

### Information: 
Movie(s) I have this with: All
Quality of the movie being searched: 2140p
Providers I use: KAT, TPB, Torrentz.eu
Version of CouchPotato: 89fd4e11 (‎24‎/‎01‎/‎2016‎ ‎8‎:‎42‎:‎44‎ ‎PM)

Running on: Synology NAS

**Comment by blade316** [comment]
@achandab 

1. please include a screenshot of your quality profile settings, including your file size settings (turn on advanced setting for this)
2. turn on debug in your CP advanced settings and include some logs of one or two movies it does this with, and we can have a look.

**Comment by achandab** [comment]
Issue has been resolved, i had all qualities checked. So i unchecked all and just left 2140p checked. Now when a movie gets searched it downloads 2140p first. Is that the correct way to set it up?

**Comment by blade316** [comment]
@achandab How you configure it is completely up to you .... if you create corresponding categories you can really make searches very efficient. .... I recommend you read up on Quality and Categories.

**Comment by achandab** [comment]
cheers. What i meant is that if i only want 2160p downloaded if available before anything else should i only check 2160p? I spent all day reading about qualities and understand most of it but i think trial and error has been the bet way to learn. Thanks again mate!

**Comment by blade316** [comment]
If you ONLY want 2160p downloaded, then its best to only select 2160p, and to make it even smarter, create a corresponding 2160p category.

1. So go into your categories and create a new one
2. name it '2160p'
3. in the required field enter 2160p (this will make sure any results without 2160p in the title are ignored) ... you can also add any other required words if needed.
4. make sure you refresh the page after this
5. drag the 2160p category to the top of the categories order list
6. also make sure that your global filters will not interfere with the 2160p category ... i.e. if most 2160p releases have 'DTS-HD' in the title, make sure 'DTS-HD' isn't in your global ignored words etc ... you get the idea
7. In your qualities section, enable advanced and confirm your 2160p sizes are accurate
8. Then to make it easier when adding a movie, drag the 2160p item to the top of your qualities order list (make sure you refresh the page after this)

Now add a movie and select 2160p for the quality and 2160p for the category and watch the magic 👍

**Comment by achandab** [comment]
yes creating a separate category makes sense now. Awesome, thanks for the explanation mate!
